# Generated by Django 3.0.3 on 2020-02-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskassign', '0003_dept_assign_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_assign_task',
            name='user',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
