# Generated by Django 3.0.3 on 2020-02-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('taskassign', '0005_auto_20200223_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_assign_task',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dept_assign_task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Profile'),
        ),
    ]
