# Generated by Django 3.0.3 on 2020-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskassign', '0008_auto_20200224_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_assign_task',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
