# Generated by Django 3.0.3 on 2020-02-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskassign', '0009_auto_20200225_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_assign_task',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
